(defun color-theme-papercup ()
  (interactive)
  (color-theme-install
   '(color-theme-papercup
     ((background-color . "#1d1d1d")
      (background-mode . dark)
      (border-color . "#1d1d1d")
      (cursor-color . "#A7A7A7")
      (foreground-color . "#f0f0f0")
      (mouse-color . "red"))
     (default ((t (:background "#1d1d1d" :foreground "#F8F8F8"))))
     (blue ((t (:foreground "red"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))

     (font-lock-builtin-face ((t (:foreground "#F9BE75"))))
     (font-lock-comment-face ((t (:italic nil :foreground "#a2a2a2"))))
     (font-lock-constant-face ((t (:foreground "#D8FA3C"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:bold nil :foreground "#F9BE75"))))
     (font-lock-keyword-face ((t (:foreground "#F9757D"))))
     (font-lock-preprocessor-face ((t (:bold t :foreground "#E3E2B1"))))
     (font-lock-reference-face ((t (:foreground "blue"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "white"))))
     (font-lock-string-face ((t (:foreground "#B1E3E2"))))
     (font-lock-type-face ((t (:foreground "#E3E2B1"))))
     (font-lock-variable-name-face ((t (:bold nil :foreground "#E7F975"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))

     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (region ((t (:background "#37283E"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))
     (underline ((nil (:underline nil))))
     (zmacs-region ((t (:background "snow" :foreground "red")))))))

(provide 'color-theme-papercup)
